// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6v180_APTCIjc9Fo7-riKYkEHEDvqKAk',
    appId: '1:923562732247:android:32abec4230bf7e39925e92',
    messagingSenderId: '923562732247',
    projectId: 'mrhouse-daf9c',
    databaseURL: 'https://mrhouse-daf9c-default-rtdb.firebaseio.com',
    storageBucket: 'mrhouse-daf9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGcAEqDu5EUzziEMY5QfVArqM0KajgC8E',
    appId: '1:923562732247:ios:f5388ecd2a254d4e925e92',
    messagingSenderId: '923562732247',
    projectId: 'mrhouse-daf9c',
    databaseURL: 'https://mrhouse-daf9c-default-rtdb.firebaseio.com',
    storageBucket: 'mrhouse-daf9c.appspot.com',
    androidClientId: '923562732247-qca3qj5ovuvl46uc49516n7n6kg17htg.apps.googleusercontent.com',
    iosClientId: '923562732247-bm0qsaq1452748ma3r91hpaihmrvnaa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.graddProj',
  );
}
